name: Build Visuals
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib numpy
      - name: Generate visuals
        run: |
          python scripts/gen_visuals.py
          python scripts/gen_visuals_v7.py || true
      - name: Commit visuals
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: add/update visuals'
          file_pattern: docs/*.png

name: Build Visuals
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib numpy
      - name: Generate visuals
        run: |
          python scripts/gen_visuals.py
          python scripts/gen_visuals_v7.py || true
      - name: Commit visuals
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: add/update visuals'
          file_pattern: docs/*.png
